# Generated by Django 4.2.30 on 2026-04-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('insight_text', models.TextField(help_text='AI-generated insight text')),
                ('category', models.CharField(choices=[('trend', 'Trend'), ('correlation', 'Correlation'), ('anomaly', 'Anomaly'), ('summary', 'Summary'), ('recommendation', 'Recommendation')], default='summary', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score 0-1')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='data_upload.uploadeddataset')),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
