# Generated by Django 4.2.30 on 2026-04-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='reports/%Y/%m/')),
                ('format', models.CharField(choices=[('pdf', 'PDF')], default='pdf', max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('includes_analysis', models.BooleanField(default=True)),
                ('includes_insights', models.BooleanField(default=True)),
                ('includes_charts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='data_upload.uploadeddataset')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
