# Generated by Django 4.2.30 on 2026-04-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('descriptive', 'Descriptive Statistics'), ('correlation', 'Correlation Analysis'), ('outlier', 'Outlier Detection'), ('trend', 'Trend Detection'), ('distribution', 'Distribution Analysis'), ('full', 'Full Analysis')], default='full', max_length=20)),
                ('results', models.JSONField(default=dict, help_text='JSON analysis output')),
                ('summary', models.TextField(blank=True, default='', help_text='Human-readable summary')),
                ('charts_data', models.JSONField(default=dict, help_text='Chart.js configuration data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='data_upload.uploadeddataset')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
